# export $(cat k8s.env | xargs)
# cat .k8s/idemploader-docs.yml | envsubst
# envsubst < .k8s/idemploader-docs.yml | kubectl apply -f -
# kubectl port-forward svc/idemploader-docs 30201:8080

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: idemploader-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idemploader-docs
  template:
    metadata:
      labels:
        app: idemploader-docs
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: ${IDEMPLOADER_DOCS_IMAGE}
        imagePullPolicy: Always
        name: idemploader-docs
        ports:
        - containerPort: 8080
        resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: idemploader-docs
  labels:
    app: idemploader-docs
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: idemploader-docs
