# export $(cat k8s.env | xargs)
# cat .k8s/idemploader-api.yml | envsubst
# envsubst < .k8s/idemploader-api.yml | kubectl apply -f -
# kubectl port-forward svc/idemploader-api 30200:3000

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: idemploader-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idemploader-api
  template:
    metadata:
      labels:
        app: idemploader-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: ${IDEMPLOADER_API_IMAGE}
        imagePullPolicy: Always
        name: idemploader-api
        ports:
        - containerPort: 3000
        resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "100m"
        env:
        - name: GIN_MODE
          value: "release"
        - name: IDEMPLOADER_S3_HOST
          value: "${IDEMPLOADER_S3_HOST}"
        - name: IDEMPLOADER_S3_ACCESS_KEY
          value: "${IDEMPLOADER_S3_ACCESS_KEY}"
        - name: IDEMPLOADER_S3_ACCESS_SECRET
          value: "${IDEMPLOADER_S3_ACCESS_SECRET}"
        - name: IDEMPLOADER_S3_BUCKET
          value: "${IDEMPLOADER_S3_BUCKET}"
        - name: IDEMPLOADER_S3_PATH
          value: "${IDEMPLOADER_S3_PATH}"
        - name: IDEMPLOADER_HOST
          value: "${IDEMPLOADER_HOST}"
        - name: IDEMPLOADER_ALLOWED_ACCESS_TOKEN
          value: "${IDEMPLOADER_ALLOWED_ACCESS_TOKEN}"
---
apiVersion: v1
kind: Service
metadata:
  name: idemploader-api
  labels:
    app: idemploader-api
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: idemploader-api
