version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IDEMPLOADER_API_IMAGE}
    ports:
      - "7100:80"
    environment:
      - GIN_MODE=${GIN_MODE:-release}
      - IDEMPLOADER_S3_HOST=${IDEMPLOADER_S3_HOST}
      - IDEMPLOADER_S3_ACCESS_KEY=${IDEMPLOADER_S3_ACCESS_KEY}
      - IDEMPLOADER_S3_ACCESS_SECRET=${IDEMPLOADER_S3_ACCESS_SECRET}
      - IDEMPLOADER_S3_BUCKET=${IDEMPLOADER_S3_BUCKET}
      - IDEMPLOADER_S3_PATH=${IDEMPLOADER_S3_PATH}
      - IDEMPLOADER_HOST=${IDEMPLOADER_HOST:-http://localhost:8080}
      - IDEMPLOADER_ALLOWED_ACCESS_TOKEN=${IDEMPLOADER_ALLOWED_ACCESS_TOKEN}
  docs:
    build:
      context: docs/
      dockerfile: Dockerfile
    image: ${IDEMPLOADER_DOCS_IMAGE}
    ports:
      - "7101:8080"
