name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      
      - name: Docker login
        run: docker login --username ${{ secrets.DOCKER_LOGIN }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API docker image
        run: docker build --tag wailorman/wailorman:idemploader_api_${{ github.sha }} .

      - name: Build Docs docker image
        run: docker build --tag wailorman/wailorman:idemploader_docs_${{ github.sha }} docs/

      - name: Push API docker image
        run: docker push wailorman/wailorman:idemploader_api_${{ github.sha }}

      - name: Push Docs docker image
        run: docker push wailorman/wailorman:idemploader_docs_${{ github.sha }}
      
      - name: Create K8S directories
        run: mkdir -p ./tmp/.k8s/
      
      - name: Populate API deployment configuration
        run: cat ./.k8s/idemploader-api.yml | envsubst > ./tmp/.k8s/idemploader-api.yml
        env:
          IDEMPLOADER_API_IMAGE: "wailorman/wailorman:idemploader_api_${{ github.sha }}"
      
      - name: Populate Docs deployment configuration
        run: cat ./.k8s/idemploader-docs.yml | envsubst > ./tmp/.k8s/idemploader-docs.yml
        env:
          IDEMPLOADER_DOCS_IMAGE: "wailorman/wailorman:idemploader_docs_${{ github.sha }}"
          
      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show ${{ secrets.DIGITALOCEAN_K8S_CLUSTER_NAME }} > ./tmp/.k8s/config

      - name: Apply API deployment configuration to the cluster
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: --kubeconfig=./tmp/.k8s/config apply -f ./tmp/.k8s/idemploader-api.yml -n idemploader

      - name: Apply Docs deployment configuration to the cluster
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: --kubeconfig=./tmp/.k8s/config apply -f ./tmp/.k8s/idemploader-docs.yml -n idemploader
      
      - name: Verify API deployment
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: --kubeconfig=./tmp/.k8s/config rollout status deployment/idemploader-api -n idemploader
      
      - name: Verify Docs deployment
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: --kubeconfig=./tmp/.k8s/config rollout status deployment/idemploader-docs -n idemploader
